name: Deploy
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Code
      uses: actions/setup-node@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: npm install
    - run: npm run deploy
